services:
  - type: web
    name: nocodb
    env: node
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      pnpm install
    startCommand: pnpm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
